info:
  app:
    name: property-api
    description: Property Api
    version: @project.version@

server:
  port: 2000
  context-path: /property-api

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: property-api
  jpa:
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

logging:
  config: classpath:logback.xml
