info:
  app:
    name: property-api
    description: Music Repository Api
    version: @project.version@

server:
  port: 2000
  context-path: /property-api

spring:
  application:
    name: property-api

logging:
  config: classpath:logback.xml
